name: mllm-msr
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - torchaudio>=2.1.0
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - pillow
  - scikit-learn
  - ninja
  - pip
  - pip:
      - -r requirements.txt
